# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 085b61f2656ea040bd7cc341785a173e6379ef89981b3f198e9e7b3bad2f9f9310de6343091cd8d9b1c5033c91b144f65e39df8e94bf0cde86b143330d557cbe

test:
  secret_key_base: eacf477804ddcfff851c3533b41a8c61862d784c1cf3b9187c7c2453783df96237a627f5ea9f7b8795974811966452572240da93364f2d0204562e5b9459a552

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
